version: '3.1'
services:
  nginx:
    container_name: nginx
    # use alpine's nginx image alternative debian base, more info at:
    # https://stackoverflow.com/questions/31833583/nginx-gives-an-internal-server-error-500-after-i-have-configured-basic-auth
    image: nginx:1.20-alpine
    restart: always
    volumes:
      - ./resources/nginx:/usr/share/nginx
      - ./config/compose/auth.htpasswd:/etc/nginx/conf.d/auth.htpasswd
      - ./config/compose/domain.crt:/etc/nginx/conf.d/domain.crt
      - ./config/compose/domain.key:/etc/nginx/conf.d/domain.key
      - ./config/compose/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 443:443
      - 5000:5000
      - 8080:8080

  registry:
    image: registry:2.7.1
    container_name: registry
    restart: always
    volumes:
      - ./resources/registry:/var/lib/registry
